[package]
name = "leptos-ezs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Eazy global state management for leptos."
readme = "../../README.md"
keywords = ["leptos", "state", "global", "di", "dependency-injection"]

[dependencies]
leptos-ezs-macros.workspace = true
leptos-ezs-core.workspace = true
