cargo-features = ["per-package-target"]

[package]
name = "leptos-ezs-core"
# default-target = "wasm32-unknown-unknown"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core functionalities for leptos-ezs."

[dependencies]
portaldi.workspace = true
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.96"
async-trait = "0.1.68"
leptos = { version = "0.6.5", features = ["nightly"] }   #TODO

[features]
default = []
